name: app_amostra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
module:
    androidPackage: com.example.app_amostra
    iosBundleIdentifier: com.example.app_amostra
flutter:
  uses-material-design: true
  assets: 
   - assets/jogos.json
   - img/
